apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tekton.dev/v1beta1","kind":"Pipeline","metadata":{"annotations":{},"name":"buildah-deploy","namespace":"default"},"spec":{"params":[{"default":"aolda/sample-image","description":"Docker image name","name":"image-repo","type":"string"},{"default":"https://github.com/aolda/sample-repo","description":"Git repo url.","name":"git-repo-url","type":"string"},{"default":"main","description":"Revision","name":"revision","type":"string"},{"default":"./Dockerfile","description":"Path of Dockerfile","name":"dockerfile","type":"string"}],"tasks":[{"name":"clone-repository","params":[{"name":"url","value":"$(params.git-repo-url)"},{"name":"revision","value":"$(params.revision)"},{"name":"deleteExisting","value":"true"}],"taskRef":{"kind":"Task","name":"git-clone"},"workspaces":[{"name":"output","workspace":"pipeline-shared-data"}]},{"name":"build-image","params":[{"name":"IMAGE","value":"$(params.image-repo):$(tasks.clone-repository.results.commit)"},{"name":"DOCKERFILE","value":"$(params.dockerfile)"}],"runAfter":["clone-repository"],"taskRef":{"kind":"Task","name":"buildah"},"workspaces":[{"name":"source","workspace":"pipeline-shared-data"}]}],"workspaces":[{"description":"This workspace will be shared throughout all steps.\n","name":"pipeline-shared-data"}]}}
      
  creationTimestamp: '2023-11-07T14:31:30Z'
  generation: 2
  name: buildah-deploy
  namespace: default
  resourceVersion: '14810395'
  uid: 0ed2e0ef-dcad-4dd1-9185-af2217b4d04f
spec:
  params:
    - default: aolda/sample-image
      description: Docker image name
      name: image-repo
      type: string
    - default: https://github.com/aolda/sample-repo
      description: Git repo url.
      name: git-repo-url
      type: string
    - default: main
      description: Revision
      name: revision
      type: string
    - default: ./Dockerfile
      description: Path of Dockerfile
      name: dockerfile
      type: string
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: $(params.git-repo-url)
        - name: revision
          value: $(params.revision)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-shared-data
    - name: build-image
      params:
        - name: IMAGE
          value: $(params.image-repo):$(tasks.clone-repository.results.commit)
        - name: DOCKERFILE
          value: $(params.dockerfile)
      runAfter:
        - clone-repository
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: pipeline-shared-data
  workspaces:
    - description: |
        This workspace will be shared throughout all steps.
        
      name: pipeline-shared-data